#!/bin/bash
DELTA="./target/release/delta --no-gitconfig --color-only"
GIT_ARGS="log --patch --stat --numstat"
diff -u <(git $GIT_ARGS | perl -pe 's/\e\[[0-9;]*[mK]//g') <(git $GIT_ARGS | $DELTA | perl -pe 's/\e\[[0-9;]*[mK]//g')
