#!/bin/bash
GIT_ARGS="log --patch --stat --numstat"
diff -u <(git $GIT_ARGS | perl -pe 's/\e\[[0-9;]*[mK]//g') <(git $GIT_ARGS | ./target/release/delta --color-only | perl -pe 's/\e\[[0-9;]*[mK]//g')
