#!/bin/bash

# if first arg provided, use it, otherwise default to release
DELTA_BIN=${1:-./target/release/delta}
DELTA="$DELTA_BIN --no-gitconfig"

foreground_color=red
for decoration_attr in box underline plain; do
    git show | $DELTA --commit-style $decoration_attr
    git show | $DELTA --file-style $decoration_attr
done
