name: Deploy Manual

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.14'

      - name: Build manual
        run: mdbook build
        working-directory: manual

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: manual/book
