name: Publish to WinGet

on:
  release:
    types: [published]

jobs:
  publish-to-winget:
    name: Publish to WinGet
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: dandavison.delta
          version: ${{ github.event.release.tag_name }}
          installers-regex: '-pc-windows-msvc\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
